[Fixes #39] add .github/ISSUE_TEMPLATE/ and .github/pull_request_template.md

diff --git a/.github/workflows/python-check.yaml b/.github/workflows/python-check.yaml
--- a/.github/workflows/python-check.yaml
+++ b/.github/workflows/python-check.yaml
@@ -36,11 +36,16 @@ jobs:
       - name: run black check
         run: |
           black --check .
+      - name: Test with mypy
+        run: "mypy geonodectl --check-untyped-defs"
       - name: Lint with flake8
         run: |
           # stop the build if there are Python syntax errors or undefined names
           flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
           # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
           flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
-      - name: Test with mypy
-        run: "mypy geonodectl --check-untyped-defs"
+      - name: Check if 'Lint with flake8' step failed
+        if: steps.flake8.outcome != 'success'
+        run: |
+          echo "flake8 fails"
+          exit 1
